CREATE TABLE `data_platform_orders_header_data`
(
  `OrderID`                          int(16) NOT NULL,
  `OrderDate`                        date NOT NULL,
  `OrderType`                        varchar(3) NOT NULL,
  `OrderStatus`                      varchar(3) NOT NULL,
  `SupplyChainRelationshipID`        int(16) NOT NULL,
  `SupplyChainRelationshipBillingID` int(4) DEFAULT NULL,
  `SupplyChainRelationshipPaymentID` int(2) DEFAULT NULL,
  `Buyer`                            int(12) NOT NULL,
  `Seller`                           int(12) NOT NULL,
  `BillToParty`                      int(12) DEFAULT NULL,
  `BillFromParty`                    int(12) DEFAULT NULL,
  `BillToCountry`                    varchar(3) DEFAULT NULL,
  `BillFromCountry`                  varchar(3) DEFAULT NULL,
  `Payer`                            int(12) DEFAULT NULL,
  `Payee`                            int(12) DEFAULT NULL,
  `ContractType`                     varchar(4) DEFAULT NULL,
  `OrderValidityStartDate`           date DEFAULT NULL,
  `OrderValidityEndDate`             date DEFAULT NULL,
  `InvoicePeriodStartDate`           date DEFAULT NULL,
  `InvoicePeriodEndDate`             date DEFAULT NULL,
  `TotalNetAmount`                   float(13) NOT NULL,
  `TotalTaxAmount`                   float(13) NOT NULL,
  `TotalGrossAmount`                 float(13) NOT NULL,
  `HeaderDeliveryStatus`             varchar(2) NOT NULL,
  `HeaderBillingStatus`              varchar(2) NOT NULL,
  `HeaderDocReferenceStatus`         varchar(2) NOT NULL,
  `TransactionCurrency`              varchar(5) NOT NULL,
  `PricingDate`                      date NOT NULL,
  `PriceDetnExchangeRate`            float(8) DEFAULT NULL,
  `RequestedDeliveryDate`            date NOT NULL,
  `RequestedDeliveryTime`            time NOT NULL,
  `HeaderCompleteDeliveryIsDefined`  tinyint(1) DEFAULT NULL,
  `Incoterms`                        varchar(4) DEFAULT NULL,
  `PaymentTerms`                     varchar(4) NOT NULL,
  `PaymentMethod`                    varchar(1) NOT NULL,
  `ReferenceDocument`                int(16) DEFAULT NULL,
  `ReferenceDocumentItem`            int(6) DEFAULT NULL,
  `AccountAssignmentGroup`           varchar(2) NOT NULL,
  `AccountingExchangeRate`           float(8) DEFAULT NULL,
  `InvoiceDocumentDate`              date NOT NULL,
  `IsExportImport`                   tinyint(1) DEFAULT NULL,
  `HeaderText`                       varchar(200) DEFAULT NULL,
  `HeaderBlockStatus`                tinyint(1) DEFAULT NULL,
  `HeaderDeliveryBlockStatus`        tinyint(1) DEFAULT NULL,
  `HeaderBillingBlockStatus`         tinyint(1) DEFAULT NULL,
  `ExternalReferenceDocument`        varchar(100) DEFAULT NULL,
  `CreationDate`                     date NOT NULL,
  `CreationTime`                     time NOT NULL,
  `LastChangeDate`                   date NOT NULL,
  `LastChangeTime`                   time NOT NULL,
  `IsCancelled`                      tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`              tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`OrderID`),

    CONSTRAINT `DPFMOrdersHeaderSupplyChainRelationshipID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_scr_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DPFMOrdersHeaderSupplyChainRelationshipBillingID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`) REFERENCES `data_platform_scr_billing_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`),
    CONSTRAINT `DPFMOrdersHeaderSupplyChainRelationshipPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`) REFERENCES `data_platform_scr_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`),
    CONSTRAINT `DPFMOrdersHeaderBillToCountry_fk` FOREIGN KEY (`BillToCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMOrdersHeaderBillFromCountry_fk` FOREIGN KEY (`BillFromCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMOrdersHeaderTransactionCurrency_fk` FOREIGN KEY (`TransactionCurrency`) REFERENCES `data_platform_currency_currency_data` (`Currency`),
    CONSTRAINT `DPFMOrdersHeaderIncoterms_fk` FOREIGN KEY (`Incoterms`) REFERENCES `data_platform_incoterms_incoterms_data` (`Incoterms`),
    CONSTRAINT `DPFMOrdersHeaderPaymentTerms_fk` FOREIGN KEY (`PaymentTerms`) REFERENCES `data_platform_payment_terms_payment_terms_data` (`PaymentTerms`),
    CONSTRAINT `DPFMOrdersHeaderPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
